version: '3'

# set up a persistable file system (for MySQL)
volumes:
  database_data:
    driver: local

#  define the three containers that will make up our build
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php

  php:
    build: ./Docker/php/
    expose:
      - 9000
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:latest
    expose:
      - 3306
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
