version: '3'

#  define the two containers that will make up our build
services:
  php:
    build: ./Docker/php/
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
    links:
      - crypto_db

  crypto_db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=cryptoklout
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=cryptokl_local
      - MYSQL_USER=crypto_local
      - MYSQL_PASSWORD=password
